# Generated by Django 5.1 on 2024-08-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0002_profile_created_at_profile_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.FloatField(default=0.0, help_text='Height in cm'),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.FloatField(default=0.0, help_text='Weight in kg'),
        ),
    ]
