# Generated by Django 5.1 on 2024-08-31 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Workout', max_length=100)),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
                ('notes', models.TextField(blank=True)),
                ('estimated_calories', models.IntegerField(default=0, help_text='Estimated calories burned (0 for unknown)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StrengthExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(default=1)),
                ('reps', models.IntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, help_text='Weight in kg(0 for bodyweight)', max_digits=5)),
                ('rest_time', models.IntegerField(default=0, help_text='Rest time between sets in seconds')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts_app.workout')),
            ],
        ),
        migrations.CreateModel(
            name='CardioExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, help_text='Distance in km', max_digits=5)),
                ('average_heart_rate', models.IntegerField(default=0)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts_app.workout')),
            ],
        ),
    ]
