# Generated by Django 5.1 on 2024-08-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
