# Generated by Django 5.1 on 2024-08-31 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts_app', '0002_alter_workout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.DurationField(help_text='Duration of workout'),
        ),
        migrations.CreateModel(
            name='YogaExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus', models.CharField(choices=[('Flexibility', 'Flexibility'), ('Strength', 'Strength'), ('Balance', 'Balance'), ('Body', 'Body'), ('Mind', 'Mind'), ('Breath', 'Breath'), ('Back', 'Back'), ('Chest', 'Chest'), ('Shoulders', 'Shoulders'), ('Arms', 'Arms'), ('Legs', 'Legs')], default='Body', max_length=100)),
                ('rest_time', models.IntegerField(default=0, help_text='Rest time between sets in seconds')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts_app.workout')),
            ],
        ),
    ]
