# Generated by Django 5.1 on 2024-09-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts_app', '0006_alter_workoutsettings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.DurationField(default='00:00', help_text='Duration of workout'),
        ),
    ]
