# Generated by Django 5.1 on 2024-09-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts_app', '0007_alter_workout_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsettings',
            name='days_ahead',
        ),
        migrations.RemoveField(
            model_name='workoutsettings',
            name='days_behind',
        ),
        migrations.AddField(
            model_name='workoutsettings',
            name='default_workout_list',
            field=models.CharField(choices=[('user', "User's Workouts"), ('all', 'All Workouts'), ('favorites', 'Favorite Workouts'), ('recent', 'Recent Workouts'), ('popular', 'Popular Workouts'), ('newest', 'Newest Workouts')], default='user', max_length=100),
        ),
        migrations.AddField(
            model_name='workoutsettings',
            name='workouts_per_page',
            field=models.IntegerField(default=10),
        ),
    ]
