# Generated by Django 5.1 on 2024-09-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts_app', '0008_remove_workoutsettings_days_ahead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardioexercise',
            name='estimated_calories',
            field=models.IntegerField(default=0, help_text='Estimated calories burned (0 for unknown)'),
        ),
        migrations.AddField(
            model_name='strengthexercise',
            name='estimated_calories',
            field=models.IntegerField(default=0, help_text='Estimated calories burned (0 for unknown)'),
        ),
        migrations.AddField(
            model_name='yogaexercise',
            name='estimated_calories',
            field=models.IntegerField(default=0, help_text='Estimated calories burned (0 for unknown)'),
        ),
    ]
