# Generated by Django 5.1 on 2024-09-01 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts_app', '0009_cardioexercise_estimated_calories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exercise_type', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('yoga', 'Yoga')], max_length=20)),
                ('focus', models.CharField(blank=True, choices=[('Full Body', 'Full Body'), ('Back', 'Back'), ('Chest', 'Chest'), ('Shoulders', 'Shoulders'), ('Arms', 'Arms'), ('Legs', 'Legs'), ('Core', 'Core'), ('Flexibility', 'Flexibility'), ('Balance', 'Balance'), ('Mind', 'Mind'), ('Breath', 'Breath')], max_length=100)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('average_heart_rate', models.IntegerField(blank=True, null=True)),
                ('rest_time', models.IntegerField(blank=True, help_text='Rest time in seconds', null=True)),
                ('estimated_calories', models.IntegerField(blank=True, help_text='Estimated calories burned', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='strengthexercise',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='yogaexercise',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='workoutsettings',
            name='default_workout_list',
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts_app.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workouts_app.workout')),
            ],
        ),
        migrations.DeleteModel(
            name='CardioExercise',
        ),
        migrations.DeleteModel(
            name='StrengthExercise',
        ),
        migrations.DeleteModel(
            name='YogaExercise',
        ),
    ]
