# Generated by Django 5.1 on 2024-09-01 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts_app', '0010_exercise_remove_strengthexercise_workout_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='distance',
            new_name='default_distance',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='average_heart_rate',
            new_name='default_reps',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='reps',
            new_name='default_sets',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='weight',
            new_name='default_weight',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='estimated_calories',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='rest_time',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets',
        ),
        migrations.AddField(
            model_name='exercise',
            name='default_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='estimated_calories_per_minute',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='rest_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workoutsettings', to=settings.AUTH_USER_MODEL),
        ),
    ]
