# Generated by Django 5.1 on 2024-09-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts_app', '0012_rename_estimated_calories_per_minute_exercise_estimated_calories_per_rep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='type',
            field=models.CharField(default='', max_length=32),
        ),
    ]
