# Generated by Django 5.1 on 2024-09-29 23:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts_app', '0014_exercise_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
